name: TLA+ AI Amplifier CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tla-syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Download TLA+ tools
        run: |
          curl -L -o tla2tools.jar https://github.com/tlaplus/tlaplus/releases/download/v1.7.0/tla2tools.jar
      
      - name: Check TLA+ syntax
        run: |
          shopt -s nullglob
          for spec in specs/*.tla; do
            echo "Checking $spec..."
            java -jar tla2tools.jar -noGenerateSpecTEAnnotations "$spec"
          done

  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run Python examples
        run: |
          shopt -s nullglob
          for example in examples/*.py; do
            echo "Running $example..."
            python "$example"
          done

  build-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [tla-syntax-check, python-tests]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      
      - name: Build documentation
        run: |
          if [ -d docs ]; then
            mkdocs build
          fi